config/routes.rb
PivotalDashboard::Application.routes.draw do
  root :to => "welcome#index"

  resources :teams

  resources :people
  
  match 'admin' => 'admin/root#index'

  namespace :admin do
    resources :teams
  end

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id(.:format)))'
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :team_assignments

  has_many :teams, :through => :team_assignments

  has_many :owned_stories,
           :class_name => 'Story',
           :primary_key => 'pivotal_name',
           :foreign_key => 'owned_by'

  has_many :requested_stories,
           :class_name => 'Story',
           :primary_key => 'pivotal_name',
           :foreign_key => 'requested_by'

  default_scope :order => 'name'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :current_velocity
  has_many :stories

  def self.create_or_update(pivotal_project)
    project = self.find_or_initialize_by_id(pivotal_project.id)
    project.attributes = pivotal_project.instance_values
    project.save
    project
  end
end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessible :url, :project_id, :name, :description, :accepted_at,
                  :story_type, :estimate, :current_state, :requested_by,
                  :owned_by, :labels

  belongs_to :project

  scope :active_stories, where("current_state in ('unstarted','started','finished','delivered') and story_type != 'release'")

  scope :current, where(:current=>true).where("story_type!='release'")

  scope :accepted_after, lambda { |project_id,date|
    where('accepted_at > ?',date).
    where('project_id = ?',project_id)
  }

  scope :accepted_releases, lambda { |project_id|
    where(:project_id => project_id).
    where(:current_state => 'accepted').
    where(:story_type => 'release')
  }

  def self.create_or_update_all_from_pivotal(pivotal_project)
    pivotal_project.stories.all(
        :modified_since => (Date.today-30).to_s,
        :includedone => 'true'
      ).each do |pivotal_story|
      self.create_or_update(pivotal_story)
    end
  end

  def self.create_or_update(tracker_story)
    story = Story.find_or_initialize_by_id(tracker_story.id)
    story.attributes = tracker_story.instance_values
    story.save
    story
  end

  def self.set_current(project_id,stories)
    Story.update_all({:current=>false},{:project_id=>project_id})
    Story.update_all({:current=>true},{:project_id=>project_id,:id=>[stories.map(&:id)]})
  end

  def first_label
    labels? ? labels.split(',').first : 'none'
  end

  def short_name
    shorten(name,60)
  end

  def self.pending_release(project_id)
    our_scope = self.accepted_releases(project_id)
    last_release_date = our_scope.select(:accepted_at).order(:accepted_at).last.accepted_at rescue nil
    self.accepted_after(project_id,last_release_date)
  end

  def shorten (string, count = 30)
    if string.length >= count 
      shortened = string[0, count]
      splitted = shortened.split(/\s/)
      words = splitted.length
      splitted[0, words-1].join(" ") + ' ...'
    else 
      string
    end
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :team_assignments

  has_many :members, :through => :team_assignments, :source => :person

  has_many :owned_stories, :through => :members, :class_name => 'Story'

end

app/models/team_assignment.rb
class TeamAssignment < ActiveRecord::Base
  belongs_to :team
  belongs_to :person
end

app/controllers/admin/root_controller.rb
class Admin::RootController < ApplicationController
  def index
  end
end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :load_build_feed
  private
    def load_build_feed
      #FIXME: Move the feed url to the Project and set a CI type
      @build_feed = nil
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.find(:all)
  end

  def show
    @person = Person.find(params[:id])
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end
  def show
    @team = Team.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @stories = Story.current.includes(:project).group_by(&:current_state)
  end

  def chatter
    @activity_feed = Feedzirra::Feed.fetch_and_parse("https://www.pivotaltracker.com/user_activities/6719535ac5ba30ac90329524c0d0aa43")
  end
end

app/helpers/admin/teams_helper.rb
module Admin::TeamsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def build_state(feed)
    (feed && build_successful?(feed)) ? 'good' : 'bad'
  end
  
  def build_status(feed)
    (feed && build_successful?(feed)) ? 'Current build is good' : 'Houston, we have a problem'
  end
  
  def icon_url(story)
    base_url = 'https://cdn1-pivotaltracker.pantherssl.com/images/v7/application/stories_view/icons'
    icon = case story.story_type
      when 'chore' then 'chore.png'
      when 'feature' then 'feature.png'
      when 'bug' then 'bug.png'
      when 'release' then 'release.png'
    end
    "#{base_url}/#{icon}"
  end
  
  def story_class(story)
    case story.current_state
      when 'accepted', 'delivered', 'finished' then 'done'
      when 'started' then 'started'
      else ''
    end
  end
  
  private
    def build_successful?(feed)
      feed && feed.entries.first.title.include?('success')
    end
end

app/views/admin/_navigation.html.haml
.navigation
  %ul
    %li.first
      =link_to_unless_current 'Teams', admin_teams_path

app/views/admin/root/index.html.haml
=render :partial => 'admin/navigation'
%h2
  Admin

app/views/layouts/applicaiton.html.haml
!!! html
%html
  %head
    %meta{:charset=>'utf-8'}
    %title Pivotal Dashboard
    %link{:rel=>'stylesheet',:href=>'/stylesheets/pivotal.css'}
    %meta{:name=>'viewport',:content=>'width=device-width, initial-scale=1'}
  %body{:lang=>'en'}
    .header
      %h1{:class => build_state(@build_feed)}
        =build_status(@build_feed)
    .content
      =yield

app/views/layouts/application.haml
!!! html
%html
  %head
    %meta{:charset=>'utf-8'}
    %title Pivotal Dashboard
    %link{:rel=>'stylesheet',:href=>'/stylesheets/pivotal.css'}
    %meta{:name=>'viewport',:content=>'width=device-width, initial-scale=1'}
  %body{:lang=>'en'}
    .header
      %h1{:class => build_state(@build_feed)}
        =build_status(@build_feed)
    .content
      =yield

app/views/layouts/application.html.haml
!!! html
%html
  %head
    %meta{:charset=>'utf-8'}
    %title Pivotal Dashboard
    %link{:rel=>'stylesheet',:href=>'/stylesheets/pivotal.css'}
    %meta{:name=>'viewport',:content=>'width=device-width, initial-scale=1'}
    =javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js'
  %body{:lang=>'en'}
    .header
      %h1{:class => build_state(@build_feed)}
        =build_status(@build_feed)
    .navigation
      %ul
        %li.first
          =link_to_unless_current "Story Board", root_path
        %li
          =link_to_unless_current "Teams Board", teams_path
        %li
          =link_to_unless_current "People Board", people_path
        %li
          =link_to_unless_current "Admin", admin_path
    .content
      =yield

app/views/people/_person.html.haml
%h2
  =link_to person.name, "http://hub.g5platform.com/people/#{person.name.downcase.gsub(' ','.')}", :target => '_blank'
%h3
  %p
    Pivotal Name:
    %span.data
      =person.pivotal_name
  %p
    Twitter Handle:
    %span.data
      =link_to person.twitter_handle, "http://twitter.com/#{person.twitter_handle}", :target => '_blank' unless person.twitter_handle.blank?
  %p
    Github Handle:
    %span
      =link_to person.github_handle, "http://github.com/#{person.github_handle}", :target => '_blank' unless person.github_handle.blank?
  %p
    Member of
    .navigation
      %ul
        =render :partial => 'team', :collection => person.teams
= render :partial => 'welcome/story', :collection => person.owned_stories.active_stories
.clear
%hr
= render :partial => 'welcome/story', :collection => person.owned_stories - person.owned_stories.active_stories
.clear

app/views/people/_team.html.haml
%li
  =link_to team.name, team_path(team)

app/views/people/index.html.haml
%h2
  People
=render :partial => 'person', :collection => @people

app/views/people/show.html.haml
=render :partial => 'person', :locals => {:person => @person}

app/views/team/_team.html.haml
%h2
  = team.name 
  (
  = team.owned_stories.active_stories.count
  \/
  = team.owned_stories.active_stories.sum('stories.estimate')
  |
  = team.owned_stories.count
  \/
  = team.owned_stories.sum('stories.estimate')
  )
.clear
= render :partial => 'member', :collection => team.members
%br

app/views/welcome/_stor.html.haml
- if story
  .story{:class => story_class(story)}
    %p.header{:class => story.current_state}
      =image_tag(icon_url(story))
      %a{:href=>story.url,:target=>'_blank'}
        =story.id
      %span
        =story.estimate
        points
    %p.body
      =story.name
    %p.footer
      #{story.project.name} / #{story.first_label}
      %span.owner
        =story.owned_by

app/views/welcome/_story.haml
- if story
  .story{:class => story_class(story)}
    %p.header{:class => story.current_state}
      =image_tag(icon_url(story))
      %a{:href=>story.url,:target=>'_blank'}
        =story.id
      %span
        =story.estimate
        points
    %p.body
      =story.name
    %p.footer
      #{story.project.name} / #{story.first_label}
      %span.owner
        =story.owned_by

app/views/welcome/_story.html.haml
- if story
  .story{:class => story_class(story)}
    %p.header{:class => story.current_state}
      =image_tag(icon_url(story))
      %a{:href=>story.url,:target=>'_blank'}
        =story.id
      %span
        -if story.estimate == -1
          Not Estimated
        -else
          ="#{story.estimate} points" unless story.estimate.blank?
    %p.body
      =story.short_name
    %p.footer
      #{story.project.name} / #{story.first_label}
      %span.owner
        =story.owned_by
      %br
      %span.status
        =story.current_state

app/views/welcome/chatter.haml
.activities
  %h2 Recently Heard...
  - @activity_feed.entries.each do |item|
    .activity
      = distance_of_time_in_words(Time.now,item.updated).titleize
      ago
      = item.content

app/views/welcome/chatter.html.haml
.activities
  %h2 Recently Heard...
  - @activity_feed.entries.each do |item|
    .activity
      = distance_of_time_in_words(Time.now,item.updated).titleize
      ago
      = item.content

app/views/welcome/index.haml
.stories
  %table.kanban
    %tr
      %td
        %h2 Upcoming
        - if @stories['unstarted']
          =render :partial => 'story', :collection => @stories['unstarted']
        - else
          No more stories in current iteration.
      %td
        %h2 In Progress
        - if @stories['started'] || @stories['finished']
          =render :partial => 'story', :collection => @stories['started'].to_a|@stories['finished'].to_a
        - else
          All stories in current iteration have been delivered.
      %td
        %h2 Pending Acceptance
        - if @stories['delivered']
          =render :partial => 'story', :collection => @stories['delivered']
        - else
          All stories in current iteration have been accepted.
      %td.last
        %h2 Ready for Release
        - PIVOTAL_PROJECTS.each do |project_id|
          =render :partial => 'story', :collection => Story.pending_release(project_id)

app/views/welcome/index.html.haml
.stories
  %table.kanban
    %tr
      %td
        %h2 Upcoming
        - if @stories['unstarted']
          =render :partial => 'story', :collection => @stories['unstarted']
        - else
          No more stories in current iteration.
      %td
        %h2 In Progress
        - if @stories['started'] || @stories['finished']
          =render :partial => 'story', :collection => @stories['started'].to_a|@stories['finished'].to_a
        - else
          All stories in current iteration have been delivered.
      %td
        %h2 Pending Acceptance
        - if @stories['delivered']
          =render :partial => 'story', :collection => @stories['delivered']
        - else
          All stories in current iteration have been accepted.
      %td.last
        %h2 Ready for Release
        - PIVOTAL_PROJECTS.each do |project_id|
          =render :partial => 'story', :collection => Story.pending_release(project_id)